<?php

namespace App\Http\Controllers\Admin\Inventory\Equipment;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use PDF;
use Storage;

class ReportController extends Controller
{
    
    public function get_records($year){
        $items = DB::select("SELECT COUNT(CONCAT(`ieid`.`ieid_id`,'-',t.`iep_id`)) as 'qty', ien.`ien_name`, iet.`iet_type`, ieb.`ieb_brand`, iep.`iep_place`, ieid.ieid_category, ieid.ieid_unit,
        COUNT(CASE WHEN t.`jan`=1 AND t.`jan_del`=0 THEN t.`jan` END) as 'jan_1',
         COUNT(CASE WHEN t.`jan`=0 AND t.`jan_del`=0 THEN t.`jan` END) as 'jan_0',
         COUNT(CASE WHEN t.`feb`=1 AND t.`feb_del`=0 THEN t.`feb` END) as 'feb_1',
         COUNT(CASE WHEN t.`feb`=0 AND t.`feb_del`=0 THEN t.`feb` END) as 'feb_0',
         COUNT(CASE WHEN t.`mar`=1 AND t.`mar_del`=0 THEN t.`mar` END) as 'mar_1',
         COUNT(CASE WHEN t.`mar`=0 AND t.`mar_del`=0 THEN t.`mar` END) as 'mar_0',
         COUNT(CASE WHEN t.`apr`=1 AND t.`apr_del`=0 THEN t.`apr` END) as 'apr_1',
         COUNT(CASE WHEN t.`apr`=0 AND t.`apr_del`=0 THEN t.`apr` END) as 'apr_0',
         COUNT(CASE WHEN t.`may`=1 AND t.`may_del`=0 THEN t.`may` END) as 'may_1',
         COUNT(CASE WHEN t.`may`=0 AND t.`may_del`=0 THEN t.`may` END) as 'may_0',
         COUNT(CASE WHEN t.`jun`=1 AND t.`jun_del`=0 THEN t.`jun` END) as 'jun_1',
         COUNT(CASE WHEN t.`jun`=0 AND t.`jun_del`=0 THEN t.`jun` END) as 'jun_0',
         COUNT(CASE WHEN t.`jul`=1 AND t.`jul_del`=0 THEN t.`jul` END) as 'jul_1',
         COUNT(CASE WHEN t.`jul`=0 AND t.`jul_del`=0 THEN t.`jul` END) as 'jul_0',
         COUNT(CASE WHEN t.`aug`=1 AND t.`aug_del`=0 THEN t.`aug` END) as 'aug_1',
         COUNT(CASE WHEN t.`aug`=0 AND t.`aug_del`=0 THEN t.`aug` END) as 'aug_0',
         COUNT(CASE WHEN t.`sep`=1 AND t.`sep_del`=0 THEN t.`sep` END) as 'sep_1',
         COUNT(CASE WHEN t.`sep`=0 AND t.`sep_del`=0 THEN t.`sep` END) as 'sep_0',
         COUNT(CASE WHEN t.`oct`=1 AND t.`oct_del`=0 THEN t.`oct` END) as 'oct_1',
         COUNT(CASE WHEN t.`oct`=0 AND t.`oct_del`=0 THEN t.`oct` END) as 'oct_0',
         COUNT(CASE WHEN t.`nov`=1 AND t.`nov_del`=0 THEN t.`nov` END) as 'nov_1',
         COUNT(CASE WHEN t.`nov`=0 AND t.`nov_del`=0 THEN t.`nov` END) as 'nov_0',
         COUNT(CASE WHEN t.`dec`=1 AND t.`dec_del`=0 THEN t.`dec` END) as 'dec_1',
         COUNT(CASE WHEN t.`dec`=0 AND t.`dec_del`=0 THEN t.`dec` END) as 'dec_0'
        FROM 
        (SELECT CONCAT(t.iei_id,'_',t.iep_id) AS 'ITM_PLC', `iei_id`, `iep_id`,
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-01') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-01') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-01') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-01') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'jan',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-01') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-01') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-01') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-01') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'jan_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-02') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-02') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-02') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-02') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'feb',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-02') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-02') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-02') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-02') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'feb_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-03') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-03') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-03') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-03') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'mar',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-03') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-03') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-03') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-03') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'mar_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-04') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-04') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-04') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-04') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'apr',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-04') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-04') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-04') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-04') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'apr_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-05') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-05') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-05') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-05') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'may',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-05') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-05') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-05') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-05') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'may_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-06') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-06') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-06') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-06') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'jun',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-06') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-06') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-06') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-06') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'jun_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-07') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-07') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-07') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-07') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'jul',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-07') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-07') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-07') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-07') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'jul_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-08') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-08') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-08') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-08') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'aug',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-08') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-08') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-08') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-08') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'aug_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-09') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-09') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-09') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-09') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'sep',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-09') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-09') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-09') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-09') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'sep_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-10') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-10') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-10') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-10') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'oct',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-10') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-10') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-10') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-10') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'oct_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-11') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-11') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-11') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-11') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'nov',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-11') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-11') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-11') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-11') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'nov_del',
        IF(ISNULL((SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-12') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-12') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-12') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`ieuc_to_condition` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-12') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'dec',
        IF(ISNULL((SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-12') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)),(IF(((SELECT t2.`iep_id` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-12') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1)!=t.iep_id),NULL,(SELECT t2.`is_deleted` FROM `inventory_equipment_update_condition` t2 WHERE DATE_FORMAT(t2.ieuc_date,'%Y-%m')<=CONCAT('".$year."','-12') AND t2.iei_id=t.iei_id ORDER BY t2.ieuc_date DESC LIMIT 1))),(SELECT t1.`is_deleted` FROM `inventory_equipment_update_condition` t1 WHERE DATE_FORMAT(t1.ieuc_date, '%Y-%m')=CONCAT('".$year."','-12') AND t1.iei_id=t.iei_id AND t1.iep_id=t.iep_id ORDER BY t1.ieuc_date DESC LIMIT 1)) AS 'dec_del'
        FROM `inventory_equipment_update_condition` t 
        GROUP BY CONCAT(t.iei_id,'_',t.iep_id)) t
        LEFT JOIN inventory_equipment_item as iei 
        ON t.iei_id = iei.iei_id
        LEFT JOIN inventory_equipment_item_details as ieid 
        ON iei.ieid_id = ieid.ieid_id
        LEFT JOIN inventory_equipment_name as ien
        ON ieid.ien_id = ien.ien_id
        LEFT JOIN inventory_equipment_type as iet 
        ON ieid.iet_id = iet.iet_id
        LEFT JOIN inventory_equipment_brand ieb 
        ON ieid.ieb_id = ieb.ieb_id 
        LEFT JOIN inventory_equipment_place iep 
        ON t.iep_id = iep.iep_id
        GROUP BY CONCAT(ieid.ieid_id,'-',t.iep_id);");

        // echo json_encode($items);

        return $items;
    }

    public function index($year){
        $items = $this->get_records($year);

        // echo json_encode($items);
        return view('Admin.Inventory.Equipment.Report')
            ->with(['items' => $items, 'year' => $year]);
    }

    public function print($year){
        $items = $this->get_records($year);
        $filename = 'Equipment_Inventory_Report_'.$year;
        
        $pdf = PDF::loadView('Reports.Inventory.Equipment', compact('items', 'year', 'filename'));
        $pdf->setPaper('a4', 'landscape');
        
        return $pdf->stream($filename);
        // return view('Reports.Inventory.Equipment')
        //     ->with(['items' => $items, 'year' => $year]);
    }

}
